version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server:java8
    container_name: mc-server-1.8
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.8.8" # O Paper utiliza a 1.8.8 como versão definitiva da 1.8
      TYPE: "PAPER"
      LEVEL_TYPE: "FLAT"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      # Coloque o seu nick aqui para já nascer como administrador
      OPS: "XBox"
      # Desativa a autenticação da Mojang
      ONLINE_MODE: "FALSE"
      MOTD: "Macrosoft Restricted Area" # <-- Adicione sua mensagem aqui
    volumes:
      - ./mc-data:/data
    restart: unless-stopped