#Minecraft server properties
#Wed Jun 03 22:34:07 UTC 2026
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=
rcon.port=25575
level-seed=
allow-nether=true
gamemode=0
enable-command-block=false
server-port=25565
enable-rcon=true
enable-query=false
op-permission-level=4
generator-settings=
resource-pack=
player-idle-timeout=0
level-name=world
rcon.password=fc046d8cd0dd43dae20d6c6b
motd=Macrosoft Restricted Area
announce-player-achievements=true
force-gamemode=false
debug=false
hardcore=false
white-list=true
pvp=true
spawn-npcs=true
spawn-animals=true
generate-structures=true
snooper-enabled=true
difficulty=1
network-compression-threshold=256
level-type=FLAT
spawn-monsters=true
enforce-whitelist=true
max-players=20
use-native-transport=false
spawn-protection=16
online-mode=false
allow-flight=false
resource-pack-hash=
max-world-size=29999984
